-- seed_memory_expanded2.sql
-- Second batch of seed entries. Run after seed_memory_expanded.sql.
-- Paste into Supabase SQL editor, then run Memory: Vectorise.

-- ============================================================
-- memory_user additions
-- ============================================================

INSERT INTO memory_user (id, user_id, content, tags, embedding, created_at, updated_at) VALUES
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon prefers to discuss architecture before any code is written -- implementation follows agreement', ARRAY['preference','architecture','workflow','planning'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon uses sliding puzzle solution: compare scrambled vs solved screenshots, extract 3x3 tiles, MSE matching, count inversions for solvability', ARRAY['puzzle','algorithm','mse','tiles'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon Vercel team ID: team_HOoYAXfWxiVyXa3jQ6ieKaGE', ARRAY['vercel','team','id','deployment'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon Supabase user UUID: 22008c93-c79b-491d-b3c1-efa194c0c871 (hardcoded fallback in all Mobius apps)', ARRAY['supabase','uuid','user','identity'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon updates _map.md at the end of every development session and adds hard-won lessons to claude_journal.md', ARRAY['workflow','journal','map','session'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon session start checklist: confirm MCP filesystem access, read CLAUDE.md, read claude_journal.md, read project CLAUDE.md, read _map.md', ARRAY['session','checklist','claude','mcp'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon GPR metric citation: Ong B.L. 2003, Landscape and Urban Planning 63(4) 197-211, 460+ citations', ARRAY['gpr','citation','publication','research'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon uses Century Gothic font as the UI font for all Mobius apps', ARRAY['font','ui','design','century-gothic'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon Ollama auto-starts via Task Scheduler using ollama-silent.vbs -- models available without manual startup', ARRAY['ollama','startup','scheduler','windows'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Boon uses Samsung A55 as primary mobile device with Mobius installed as PWA; Intel Arc GPU on laptop for local AI via IPEX-LLM', ARRAY['mobile','pwa','arc','ipex'], NULL, now(), now());

-- ============================================================
-- memory_project additions (GPRTool deep technical)
-- ============================================================

INSERT INTO memory_project (id, user_id, content, tags, project_ids, file_refs, embedding, created_at, updated_at) VALUES
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'GPRTool Vercel project ID: prj_oioZB5jSKFHb99IZcSxZutIcjufi', ARRAY['vercel','project-id','deployment','gpr'], ARRAY['GPRTool'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'GPRTool designNorthAngle is the primary driver -- rotates the grid, housing blocks, and all placed elements; globalNorthAngle is for future true-north alignment of imported geometry', ARRAY['north','angle','grid','housing'], ARRAY['GPRTool'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'GPRTool substrate caps table controls maximum LAI contribution per substrate type to prevent unrealistic GPR scores', ARRAY['substrate','caps','lai','gpr'], ARRAY['GPRTool'], ARRAY['plants_free.json'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'GPRTool coplanar polygon issue: when two surfaces share the same plane equation they must be separated by BFS flood-fill; otherwise polygons merge incorrectly', ARRAY['coplanar','polygon','bfs','threejs'], ARRAY['GPRTool'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'GPRTool LAI values from ORNL and TRY databases are measured in open-ground conditions and require urban calibration before use in GPRTool', ARRAY['lai','ornl','try','calibration'], ARRAY['GPRTool'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'GPRTool Singapore LAI CSV has unresolved duplicates -- must be cleaned before merging into LAI_categorised.csv', ARRAY['lai','csv','duplicates','singapore'], ARRAY['GPRTool'], ARRAY['LAI_categorised.csv'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'GPRTool GPRI Game Plan (March 2026): covers institutional vision, global franchise model, GPRTool commercialisation, corporate structure -- saved in GPRTool project folder', ARRAY['gpri','game-plan','commercial','strategy'], ARRAY['GPRTool'], ARRAY['master_log.md'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'GPRTool north point compass: N needle always points True North; green arrow points Design North; compass visible in 3D viewport', ARRAY['compass','true-north','design-north','viewport'], ARRAY['GPRTool'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'GPRTool primary demo site coordinates: 30 Beaufort Street Northbridge Perth WA -- used as default test case for all GPR calculations', ARRAY['demo','northbridge','coordinates','test'], ARRAY['GPRTool'], ARRAY[]::text[], NULL, now(), now()),

  -- Mobius_Coder deep technical
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder Vercel project ID: prj_o3wt39gLQk1URzydKfhexcCyaaQW', ARRAY['vercel','project-id','coder','deployment'], ARRAY['Mobius_Coder'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder Supabase operational DB: sfvwhbzxklscfsnyrwq.supabase.co -- tables: conversations, sessions, dev_diary, fault_log, user_profile', ARRAY['supabase','operational','tables','sessions'], ARRAY['Mobius_Coder'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder dev guide at: C:\Users\263350F\_myProjects\mobius_coder_devguide.md', ARRAY['devguide','path','reference','coder'], ARRAY['Mobius_Coder'], ARRAY['mobius_coder_devguide.md'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder mcp.json configures home folder, chats directory name, and IndexedDB key for Project: Home persistence', ARRAY['mcp','config','home','indexeddb'], ARRAY['Mobius_Coder'], ARRAY['mcp.json'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder _context folder contains: .catalogue, CLAUDE.md, log_summary.md, seed SQL files', ARRAY['context','folder','catalogue','seeds'], ARRAY['Mobius_Coder'], ARRAY['_context/CLAUDE.md'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Vercel Vercel project ID: prj_9CppPeNBf9Tj6P7FEucVlYCZXPwf; URL: mobius.vercel.app', ARRAY['vercel','project-id','mobius-vercel','url'], ARRAY['Mobius_Vercel'], ARRAY[]::text[], NULL, now(), now());

-- ============================================================
-- memory_tools additions (deep technical)
-- ============================================================

INSERT INTO memory_tools (id, user_id, content, tags, embedding, created_at, updated_at) VALUES
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'When Supabase lazy-init client throws on missing env vars, the error propagates through handler -- wrap all db() calls in try-catch', ARRAY['supabase','error','lazy-init','handler'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Gemini API text generation endpoint: https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={key}', ARRAY['gemini','api','endpoint','url'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Gemini embedding endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent?key={key} with outputDimensionality: 768', ARRAY['gemini','embedding','endpoint','url'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Groq API is used as fallback when Gemini quota is exceeded -- check error.message.includes("quota") or error.message.includes("429")', ARRAY['groq','fallback','quota','429'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Three.js north compass: create ArrowHelper pointing in Y direction for True North, rotate by designNorthAngle for Design North arrow', ARRAY['threejs','compass','arrow','rotation'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Vercel poll deployment status via REST: GET /v6/deployments?projectId={id}&teamId={id}&limit=1 with Bearer token -- check uid changes to detect new deploy', ARRAY['vercel','polling','deployment','api'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Memory semantic dedup threshold: skip insert if cosine similarity >= 0.92 with any existing entry in the target table', ARRAY['memory','dedup','cosine','threshold'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'For PowerShell bat files: use plain ^ for line continuation, avoid all special Unicode characters including smart quotes and em dashes', ARRAY['powershell','bat','unicode','continuation'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Supabase match_memories RPC must be updated with DROP FUNCTION + CREATE OR REPLACE whenever a new memory table is added to the UNION', ARRAY['supabase','rpc','union','schema'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'pgvector cosine similarity = 1 - (embedding <=> query_embedding) -- higher is more similar; values near 1.0 are near-duplicates', ARRAY['pgvector','cosine','similarity','formula'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'ivfflat index for pgvector: WITH (lists = 10) is appropriate for small tables under 1000 rows; increase lists for larger tables', ARRAY['pgvector','ivfflat','index','performance'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Browser fetch() API is available in Node.js 18+ natively -- no node-fetch package needed on Vercel serverless functions', ARRAY['nodejs','fetch','vercel','serverless'], NULL, now(), now());

-- ============================================================
-- memory_mobius additional (architecture and self-knowledge)
-- ============================================================

INSERT INTO memory_mobius (id, user_id, content, tags, app_ids, file_refs, embedding, created_at, updated_at) VALUES
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder is purpose-built as a coding agent for GPRTool debugging -- its primary use case is diagnosing and fixing GPRTool Three.js issues', ARRAY['purpose','gpr','debugging','threejs'], ARRAY['Mobius_Coder'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius ecosystem long-term goal: Mobius as AI orchestration layer, GPRTool as domain application embodying GPR research, Factory as autonomous knowledge services', ARRAY['vision','ecosystem','orchestration','factory'], ARRAY['Mobius_Coder','Mobius_Vercel','Mobius_Factory'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder memory injection: getMemoryContext() called before every AI query -- top 15 semantically relevant memories prepended to system context', ARRAY['memory','injection','context','query'], ARRAY['Mobius_Coder'], ARRAY['js/commands.js','js/memory.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder memory pipeline: raw Q+A auto-extracted to memory_general -> Memory: Distil synthesises into working tables -> Memory: Vectorise populates pgvector embeddings', ARRAY['pipeline','general','distil','vectorise'], ARRAY['Mobius_Coder'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder js/router.js implements conversational router -- assigns each query to best model by detected task category (code/debug/explain/plan/review)', ARRAY['router','routing','task','category'], ARRAY['Mobius_Coder'], ARRAY['js/router.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder js/log.js writes session chat files to chats/chat-YYYYMMDD-HHmm.md when coderRootHandle is set; fallback to _context/chat.md', ARRAY['log','session','chat','filesystem'], ARRAY['Mobius_Coder'], ARRAY['js/log.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder js/startup.js silently restores coderRootHandle from IndexedDB on every page load if browser permission is still granted', ARRAY['startup','indexeddb','handle','restore'], ARRAY['Mobius_Coder'], ARRAY['js/startup.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder api/health.js endpoint returns {ok, supabase, supabaseDetail} -- used by connectivity panel to verify Supabase connection on startup', ARRAY['health','endpoint','supabase','connectivity'], ARRAY['Mobius_Coder'], ARRAY['api/health.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder api/services/status endpoint pings all cloud AI models and returns {models: [{name, ok}]} -- used by connectivity panel Cloud AI row', ARRAY['status','models','ping','cloud'], ARRAY['Mobius_Coder'], ARRAY['api/status.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder index.html is the single-page app shell with all CSS variables, UI layout, and inline script bootstrapping -- all JS modules loaded from js/ folder', ARRAY['index','html','css','variables'], ARRAY['Mobius_Coder'], ARRAY['index.html'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder panel navigation: up/down arrow buttons in toolbar navigate between panel history -- panel.js tracks openHistory array', ARRAY['panel','navigation','history','arrows'], ARRAY['Mobius_Coder'], ARRAY['js/panel.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder response toolbar: copy, thumbs up/down, and navigation buttons appear below each AI response', ARRAY['toolbar','response','copy','thumbs'], ARRAY['Mobius_Coder'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder Project: Slim generates a condensed file index from _dev/_dev_guide.md via Gemini if the _slim.md header is missing', ARRAY['project','slim','index','gemini'], ARRAY['Mobius_Coder'], ARRAY['js/project.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder Project: Brief opens .brief file in edit panel -- Save button writes directly to _context/.brief', ARRAY['project','brief','edit','save'], ARRAY['Mobius_Coder'], ARRAY['js/project.js','_context/.brief'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder All Mode prepends brief + slim + lastReadFile content to every model query via buildContext() in all.js', ARRAY['all-mode','context','brief','slim'], ARRAY['Mobius_Coder'], ARRAY['js/all.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder Debug: Sandbox writes proposed fixes to _debug/fix/ folder only -- real source files are never touched until Debug: Promote CONFIRM is typed', ARRAY['debug','sandbox','promote','safety'], ARRAY['Mobius_Coder'], ARRAY['js/debug.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Factory folder: C:\Users\263350F\Mobius\Factory_Health -- fresh Supabase project, Gemini key shared with Mobius', ARRAY['factory','path','supabase','health'], ARRAY['Mobius_Factory'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius General Supabase memory tables: memory_general (raw), memory_user (user facts), memory_tools (tech lessons), memory_project (project decisions), memory_mobius (self-awareness)', ARRAY['memory','tables','schema','general'], ARRAY['Mobius_Coder','Mobius_Vercel'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius self-awareness goal: Mobius should know its own commands, architecture, model routing, file structure, and development history to give better coding assistance', ARRAY['self-awareness','goal','commands','architecture'], ARRAY['Mobius_Coder','Mobius_Vercel'], ARRAY[]::text[], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder Plain text (no command prefix) routes to the last used model via sendToLastModel() in commands.js', ARRAY['routing','plain-text','last-model','commands'], ARRAY['Mobius_Coder'], ARRAY['js/commands.js'], NULL, now(), now()),
  (gen_random_uuid(), '22008c93-c79b-491d-b3c1-efa194c0c871', 'Mobius_Coder css variables defined in index.html: --surface, --border, --text, --text-dim, --accent2, --bg, --font, --green, --red', ARRAY['css','variables','ui','theme'], ARRAY['Mobius_Coder'], ARRAY['index.html'], NULL, now(), now());
